service: jenkins-pipeline

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 10
  memorySize: 128
  stage: dev
  region: us-east-1

functions:
  echoBack:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /

package:
  exclude:
    - .idea/**
    - tmp/**